config/routes.rb
Rails.application.routes.draw do

  resources :links

  get 'dashboard/index'

  get ':slug' => 'links#show'

  match '/:id' => "shortener/shortened_urls#show", via: [:post, :get]

  root 'dashboard#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  after_create :generate_short_link, :get_page_title

  #this method will create a slug using Fixnum#to_s that accepts base as the argument
  def generate_short_link
    self.slug = self.id.to_s(36)
    self.save
  end

  #display short url
  def display_short_url
    ENV['BASE_URL'] + self.slug
  end

  def get_page_title
    PageTitleScrap.perform_async(self.id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  #new link object and give us most frequently accessed urls based on clicks count
  def index
    @link = Link.new
    @top_urls = Link.order(clicks: :desc).first(100)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :create]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    #if enter the short url, will redirect to original url and clicks will increase by 1
    if params[:slug]
      @link = Link.find_by_slug(params[:slug])
      if redirect_to @link.given_url
        @link.clicks += 1
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  # def edit
  # end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  # def update
  #   respond_to do |format|
  #     if @link.update(link_params)
  #       format.html { redirect_to @link, notice: 'Link was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @link }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @link.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /links/1
  # DELETE /links/1.json
  # def destroy
  #   @link.destroy
  #   respond_to do |format|
  #     format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find_by_slug(params[:slug])
      @top_urls = Link.order(clicks: :desc).first(100) #top urls based on clicks count
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:given_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/dashboard/index.html.erb
<div class="title">
  <h1>Top 100 links</h1>
</div>

<div class="row" id="links-container">
    <%= render partial: 'links/top_hundred_urls', locals:{top_urls: @top_urls} %>
</div>

app/views/layouts/_new_link.html.erb
<div class="row">
  <%= render 'links/form' %>
</div>

<div class="result"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Url Shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container-fluid">
      <%= render 'layouts/new_link' %>
      <%= yield %>
    </div>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, remote: true) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :given_url, :class => 'form-control', :placeholder => "Paste a link to shorten" %>
  </div>

  <div class="actions">
    <%= f.submit 'Shorten URL', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/links/_top_hundred_urls.html.erb
<% top_urls.each do |link| %>
    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 link">
      <p class="title"><%= link_to truncate(link.title, length: 60), link_path(link) %></p>
      <p class="short_url"><%= link_to link.display_short_url, link.slug, target: '_blank' %></p>
      <ul class="click_time">
        <li><span class="badge"><span class="clicks"><%= link.clicks %></span></span> clicks</li>
      </ul>
      <p class="long_url"><%= link_to truncate(link.given_url, length: 60), link.given_url %></p>
    </div>
<% end %>

app/views/links/create.js.erb
$('.result').html('<p class="short_url">Your Shortened URL: <%= link_to @link.display_short_url, target: "_blank" %></p>');

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Given url</th>
      <th>Slug</th>
      <th>Clicks</th>
      <th>Snapshot</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.given_url %></td>
        <td><%= link.slug %></td>
        <td><%= link.clicks %></td>
        <td><%= link.snapshot %></td>
        <td><%= link.title %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p class="title"><%= @link.title %></p>
<p class="short_url"><%= link_to @link.display_short_url, @link.display_short_url, target: '_blank' %></p>
<ul class="click_time">
  <li><span class="badge"><span class="clicks"><%= @link.clicks %></span></span> clicks</li>
</ul>

<p class="long_url"><%= link_to @link.given_url, @link.given_url %></p>

<%= link_to 'Back', root_path %>